-- Temporarily disable RLS for development
-- WARNING: Only use this in development! Re-enable RLS for production!

ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE installed_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_replies DISABLE ROW LEVEL SECURITY;
ALTER TABLE liked_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE bounties DISABLE ROW LEVEL SECURITY;
ALTER TABLE bounty_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE skill_analytics DISABLE ROW LEVEL SECURITY;